Repository facebookincubator/submitit, pull requests merged in 2020-11, with the labels that each got.

#32 Replace JobPlaceHolder by unintialized job
  submitit/core/core.py
  submitit/core/test_core.py
Labels: CLA Signed

#31 Register jobs which are unpickled
  submitit/core/core.py
  submitit/core/test_core.py
Labels: CLA Signed, enhancement

#33 Enter postmorterm when job raise in debug mode
  mypy.ini
  submitit/local/debug.py
Labels: enhancement
